### PR TITLE
Move between workspaces

### PR DESCRIPTION
**Pull request by Gabryel8818**
move between workspaces is not working

### CODE REVIEW

**Comment by gh0stzk** [comment]
In my configuration moving between workspaces is with **ctrl + super + {left, right}** arrows.

But in effect if you want to move directly to another workspace, that configuration would be missing.

**Comment by gh0stzk** [comment]
I updated that part of sxhkd `super + ctrl + 1-9` will move you to a specific desktop. `super + ctrl + shift + 1-9` will move the node to a specific desktop.

`ctrl + super + left,right` still moves throw desktops and` ctrl + super + shift + left,right` move the node throw desktops.

```bash
# focus or send to the given desktop
super + ctrl + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}' '--follow'
```

**Comment by Gabryel8818** [comment]
> But in your code, you can only move to another workspace if you have focused some node.
> 
> What are you trying to do, just move you between a specific workspace? or move a node to a specific workspace?

@gh0stzk

Previously this code allowed moving between workspaces using super + 1,2,3,4....

What would be the problem with keeping the arrows and numbers?

**Comment by Gabryel8818** [comment]
> I updated that part of sxhkd `super + ctrl + 1-9` will move you to a specific desktop. `super + ctrl + shift + 1-9` will move the node to a specific desktop.
> 
> `ctrl + super + left,right` still moves throw desktops and` ctrl + super + shift + left,right` move the node throw desktops.
> 
> ```shell
> # focus or send to the given desktop
> super + ctrl + {_,shift + }{1-9,0}
> 	bspc {desktop -f,node -d} '^{1-9,10}' '--follow'
> ```
> 
> The problem with your code is that you can't move to a specific desktop if you don't have a window focused.

this code moves a window to another desktop, my idea is different, it sets the focus to another desktop

**Pull request closed without merging**
