### PR TITLE
Fix : Translated some lines in RiceUpdater and fixed some typos

### PR DESCRIPTION
**Pull request by AzhamProdLive**
Title

### CODE REVIEW

**Comment by AzhamProdLive** [comment]
I'm gonna check for other files to translate, don't merge yet

**Comment by AzhamProdLive** [comment]
Done & Ready to merge

**Comment by gh0stzk** [comment]
Ok let me check it, im really busy last days

**Review by gh0stzk — CHANGES_REQUESTED** [review]
could pls left only the english comments.

**Review by gh0stzk — CHANGES_REQUESTED** [review]
Here are repeated lines like opt.relativenumber = true and in one is "tru". splitright and below too.

**Review by AzhamProdLive — COMMENTED** [review]
Fixed the errors, please check and tell me what you think about it

**Review by AzhamProdLive — COMMENTED** [review]
:+1:

**Comment by adilzaheem** [comment]
can you please talk about the progress so far?

**Comment by AzhamProdLive** [comment]
> can you please talk about the progress so far?

It's done, I'm waiting for merge.

**Comment by AzhamProdLive** [comment]
Not merging the translation in the end ?

**Pull request closed without merging**
